// <auto-generated />
using BrowserArcade.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrowserArcade.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721152715_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrowserArcade.Api.Models.QuizItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer0")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Answer1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Answer2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Answer3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CorrectIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuizItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer0 = "HyperText Markup Language",
                            Answer1 = "HighText Machine Language",
                            Answer2 = "Hyperlink and Text Management Language",
                            Answer3 = "Home Tool Markup Language",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "What does HTML stand for?"
                        },
                        new
                        {
                            Id = 2,
                            Answer0 = "//",
                            Answer1 = "#",
                            Answer2 = "/*",
                            Answer3 = "--",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "Which symbol is commonly used to start a comment in Python?"
                        },
                        new
                        {
                            Id = 3,
                            Answer0 = "integer",
                            Answer1 = "float",
                            Answer2 = "boolean",
                            Answer3 = "character",
                            CorrectIndex = 2,
                            Difficulty = 1,
                            Question = "Which of these is a JavaScript data type?"
                        },
                        new
                        {
                            Id = 4,
                            Answer0 = "<link>",
                            Answer1 = "<href>",
                            Answer2 = "<a>",
                            Answer3 = "<url>",
                            CorrectIndex = 2,
                            Difficulty = 1,
                            Question = "Which HTML tag is used to create a hyperlink?"
                        },
                        new
                        {
                            Id = 5,
                            Answer0 = ":",
                            Answer1 = ";",
                            Answer2 = ",",
                            Answer3 = ".",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "What symbol is commonly used to end a statement in C#?"
                        },
                        new
                        {
                            Id = 6,
                            Answer0 = "Loop",
                            Answer1 = "Function",
                            Answer2 = "Array",
                            Answer3 = "Operator",
                            CorrectIndex = 2,
                            Difficulty = 1,
                            Question = "Which of these is used to store multiple values in a single variable in many programming languages?"
                        },
                        new
                        {
                            Id = 7,
                            Answer0 = "func",
                            Answer1 = "define",
                            Answer2 = "function",
                            Answer3 = "def",
                            CorrectIndex = 3,
                            Difficulty = 1,
                            Question = "Which keyword is commonly used to define a function in Python?"
                        },
                        new
                        {
                            Id = 8,
                            Answer0 = "font-style",
                            Answer1 = "text-color",
                            Answer2 = "color",
                            Answer3 = "text-style",
                            CorrectIndex = 2,
                            Difficulty = 1,
                            Question = "Which CSS property is used to change text color?"
                        },
                        new
                        {
                            Id = 9,
                            Answer0 = "=",
                            Answer1 = "==",
                            Answer2 = ":=",
                            Answer3 = "!=",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "Which symbol is used for equality comparison in many languages like JavaScript or C#?"
                        },
                        new
                        {
                            Id = 10,
                            Answer0 = "Computer Style Sheets",
                            Answer1 = "Cascading Style Sheets",
                            Answer2 = "Creative Style System",
                            Answer3 = "Color Style Syntax",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "What does CSS stand for?"
                        },
                        new
                        {
                            Id = 11,
                            Answer0 = "<heading>",
                            Answer1 = "<h1>",
                            Answer2 = "<h6>",
                            Answer3 = "<title>",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "Which HTML tag is used to display the largest heading?"
                        },
                        new
                        {
                            Id = 12,
                            Answer0 = "Loop",
                            Answer1 = "Variable",
                            Answer2 = "Class",
                            Answer3 = "Object",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "Which programming structure repeats a block of code multiple times?"
                        },
                        new
                        {
                            Id = 13,
                            Answer0 = "Number",
                            Answer1 = "String",
                            Answer2 = "Boolean",
                            Answer3 = "Array",
                            CorrectIndex = 2,
                            Difficulty = 1,
                            Question = "What is the result type of a comparison like 5 > 3?"
                        },
                        new
                        {
                            Id = 14,
                            Answer0 = "GET",
                            Answer1 = "SELECT",
                            Answer2 = "SHOW",
                            Answer3 = "FETCH",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "Which SQL command is used to retrieve data from a database?"
                        },
                        new
                        {
                            Id = 15,
                            Answer0 = "x",
                            Answer1 = "*",
                            Answer2 = "^",
                            Answer3 = "#",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "What symbol is used for multiplication in most programming languages?"
                        },
                        new
                        {
                            Id = 16,
                            Answer0 = "String",
                            Answer1 = "Boolean",
                            Answer2 = "Integer",
                            Answer3 = "Float",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "Which of these is used to store text data?"
                        },
                        new
                        {
                            Id = 17,
                            Answer0 = "Git",
                            Answer1 = "HTML",
                            Answer2 = "CSS",
                            Answer3 = "SQL",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "Which of the following is a version control system?"
                        },
                        new
                        {
                            Id = 18,
                            Answer0 = "const",
                            Answer1 = "Python doesn't have a keyword for variables",
                            Answer2 = "var",
                            Answer3 = "new",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "Which keyword is used to create a variable in Python?"
                        },
                        new
                        {
                            Id = 19,
                            Answer0 = "<picture>",
                            Answer1 = "<img>",
                            Answer2 = "<image>",
                            Answer3 = "<src>",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "Which HTML tag is used to insert an image?"
                        },
                        new
                        {
                            Id = 20,
                            Answer0 = "Structured Query Language",
                            Answer1 = "Simple Query Language",
                            Answer2 = "Structured Question Language",
                            Answer3 = "System Query Logic",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "What does SQL stand for?"
                        },
                        new
                        {
                            Id = 21,
                            Answer0 = "+",
                            Answer1 = "&",
                            Answer2 = "%",
                            Answer3 = "//",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "Which operator is used for addition?"
                        },
                        new
                        {
                            Id = 22,
                            Answer0 = "Python",
                            Answer1 = "Java",
                            Answer2 = "HTML",
                            Answer3 = "C#",
                            CorrectIndex = 2,
                            Difficulty = 1,
                            Question = "Which of the following is NOT a programming language?"
                        },
                        new
                        {
                            Id = 23,
                            Answer0 = "repeat",
                            Answer1 = "loop",
                            Answer2 = "for",
                            Answer3 = "iterate",
                            CorrectIndex = 2,
                            Difficulty = 1,
                            Question = "Which keyword is commonly used to create a loop in many languages?"
                        },
                        new
                        {
                            Id = 24,
                            Answer0 = "To store data",
                            Answer1 = "To repeat code",
                            Answer2 = "To style a webpage",
                            Answer3 = "To compile code",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "What is the purpose of a variable?"
                        },
                        new
                        {
                            Id = 25,
                            Answer0 = "<lb>",
                            Answer1 = "<break>",
                            Answer2 = "<br>",
                            Answer3 = "<newline>",
                            CorrectIndex = 2,
                            Difficulty = 1,
                            Question = "Which HTML tag creates a line break?"
                        },
                        new
                        {
                            Id = 26,
                            Answer0 = "()",
                            Answer1 = "[]",
                            Answer2 = "{}",
                            Answer3 = "<>",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "Which bracket type is used for arrays in JavaScript?"
                        },
                        new
                        {
                            Id = 27,
                            Answer0 = "Integrated Development Environment",
                            Answer1 = "Internal Development Engine",
                            Answer2 = "Interactive Debug Engine",
                            Answer3 = "Integrated Design Editor",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "What does IDE stand for?"
                        },
                        new
                        {
                            Id = 28,
                            Answer0 = "ADD",
                            Answer1 = "INSERT",
                            Answer2 = "CREATE",
                            Answer3 = "UPDATE",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "Which SQL command is used to add new data into a table?"
                        },
                        new
                        {
                            Id = 29,
                            Answer0 = "Numbers only",
                            Answer1 = "True or False",
                            Answer2 = "Text only",
                            Answer3 = "Dates",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "What value does a Boolean variable store?"
                        },
                        new
                        {
                            Id = 30,
                            Answer0 = "<head>",
                            Answer1 = "<meta>",
                            Answer2 = "<body>",
                            Answer3 = "<script>",
                            CorrectIndex = 2,
                            Difficulty = 1,
                            Question = "Which HTML element contains the visible page content?"
                        },
                        new
                        {
                            Id = 31,
                            Answer0 = "Store files",
                            Answer1 = "Group reusable code",
                            Answer2 = "Style webpages",
                            Answer3 = "Connect databases",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "What is the purpose of a function?"
                        },
                        new
                        {
                            Id = 32,
                            Answer0 = "Kotlin",
                            Answer1 = "PHP",
                            Answer2 = "Java",
                            Answer3 = "CSS",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "Which of the following languages' variables must contain a $ prefix?"
                        },
                        new
                        {
                            Id = 33,
                            Answer0 = "send",
                            Answer1 = "result",
                            Answer2 = "output",
                            Answer3 = "return",
                            CorrectIndex = 3,
                            Difficulty = 1,
                            Question = "Which keyword is used to return a value from a function in many languages?"
                        },
                        new
                        {
                            Id = 34,
                            Answer0 = "DELETE",
                            Answer1 = "REMOVE",
                            Answer2 = "DROP",
                            Answer3 = "CLEAR",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "Which SQL command is used to remove data from a table?"
                        },
                        new
                        {
                            Id = 35,
                            Answer0 = "Converts code into machine code",
                            Answer1 = "Runs a website",
                            Answer2 = "Designs interfaces",
                            Answer3 = "Stores files",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "What does a compiler do?"
                        },
                        new
                        {
                            Id = 36,
                            Answer0 = "<ul>",
                            Answer1 = "<ol>",
                            Answer2 = "<li>",
                            Answer3 = "<list>",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "Which HTML tag is used to create an unordered list?"
                        },
                        new
                        {
                            Id = 37,
                            Answer0 = "Loop",
                            Answer1 = "Conditional",
                            Answer2 = "Variable",
                            Answer3 = "Module",
                            CorrectIndex = 1,
                            Difficulty = 1,
                            Question = "Which programming concept allows code to make decisions?"
                        },
                        new
                        {
                            Id = 38,
                            Answer0 = "if",
                            Answer1 = "when",
                            Answer2 = "case",
                            Answer3 = "check",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "Which keyword is used for conditional logic in many languages?"
                        },
                        new
                        {
                            Id = 39,
                            Answer0 = ".js",
                            Answer1 = ".java",
                            Answer2 = ".script",
                            Answer3 = ".jsx",
                            CorrectIndex = 0,
                            Difficulty = 1,
                            Question = "Which file extension is commonly used for JavaScript files?"
                        },
                        new
                        {
                            Id = 40,
                            Answer0 = "Styling websites",
                            Answer1 = "Running operating systems",
                            Answer2 = "Storing and managing data",
                            Answer3 = "Writing code",
                            CorrectIndex = 2,
                            Difficulty = 1,
                            Question = "What is a database primarily used for?"
                        },
                        new
                        {
                            Id = 41,
                            Answer0 = "POST",
                            Answer1 = "GET",
                            Answer2 = "PUT",
                            Answer3 = "DELETE",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Which HTTP method is typically used to retrieve data from a server?"
                        },
                        new
                        {
                            Id = 42,
                            Answer0 = "POST",
                            Answer1 = "GET",
                            Answer2 = "PATCH",
                            Answer3 = "HEAD",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which HTTP method is commonly used to create a new resource in REST APIs?"
                        },
                        new
                        {
                            Id = 43,
                            Answer0 = "200",
                            Answer1 = "301",
                            Answer2 = "404",
                            Answer3 = "500",
                            CorrectIndex = 2,
                            Difficulty = 2,
                            Question = "Which HTTP status code means 'Not Found'?"
                        },
                        new
                        {
                            Id = 44,
                            Answer0 = "200",
                            Answer1 = "404",
                            Answer2 = "500",
                            Answer3 = "403",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which HTTP status code indicates a successful request?"
                        },
                        new
                        {
                            Id = 45,
                            Answer0 = "Remote Execution System Technology",
                            Answer1 = "Representational State Transfer",
                            Answer2 = "Resource Execution Standard Tool",
                            Answer3 = "Remote Endpoint Service Transfer",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "In REST APIs, what does REST stand for?"
                        },
                        new
                        {
                            Id = 46,
                            Answer0 = "Stateful sessions",
                            Answer1 = "Stateless communication",
                            Answer2 = "Binary protocols",
                            Answer3 = "Encrypted payloads",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Which principle is central to REST APIs?"
                        },
                        new
                        {
                            Id = 47,
                            Answer0 = "Django",
                            Answer1 = "React",
                            Answer2 = "Laravel",
                            Answer3 = "Spring Boot",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Which JavaScript library is commonly used for building user interfaces?"
                        },
                        new
                        {
                            Id = 48,
                            Answer0 = "Java",
                            Answer1 = "TypeScript",
                            Answer2 = "Python",
                            Answer3 = "C#",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Angular is primarily written in which language?"
                        },
                        new
                        {
                            Id = 49,
                            Answer0 = "Mobile apps",
                            Answer1 = "Web applications",
                            Answer2 = "Operating systems",
                            Answer3 = "Embedded systems",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "ASP.NET is primarily used for what type of development?"
                        },
                        new
                        {
                            Id = 50,
                            Answer0 = "JavaScript",
                            Answer1 = "PHP",
                            Answer2 = "Python",
                            Answer3 = "Ruby",
                            CorrectIndex = 2,
                            Difficulty = 2,
                            Question = "Django is a web framework written in which language?"
                        },
                        new
                        {
                            Id = 51,
                            Answer0 = "Node.js",
                            Answer1 = "JRE",
                            Answer2 = ".NET",
                            Answer3 = "Next.js",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Express.js is commonly used with which runtime?"
                        },
                        new
                        {
                            Id = 52,
                            Answer0 = "Test the entire application workflow",
                            Answer1 = "Test individual components or functions",
                            Answer2 = "Test user interface design",
                            Answer3 = "Test deployment pipelines",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "What is the main purpose of unit testing?"
                        },
                        new
                        {
                            Id = 53,
                            Answer0 = "Single functions",
                            Answer1 = "Application workflow from user perspective",
                            Answer2 = "Database schema design",
                            Answer3 = "Code formatting",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "End-to-end testing primarily verifies what?"
                        },
                        new
                        {
                            Id = 54,
                            Answer0 = "Virtual machines",
                            Answer1 = "Containerization",
                            Answer2 = "Database hosting",
                            Answer3 = "Web servers",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "What does Docker primarily provide?"
                        },
                        new
                        {
                            Id = 55,
                            Answer0 = "Dockerfile",
                            Answer1 = "docker.config",
                            Answer2 = "container.json",
                            Answer3 = "build.yaml",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which file is commonly used to define how a Docker image is built?"
                        },
                        new
                        {
                            Id = 56,
                            Answer0 = "git fetch",
                            Answer1 = "git clone",
                            Answer2 = "git pull",
                            Answer3 = "git init",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Which Git command downloads a repository from a remote server?"
                        },
                        new
                        {
                            Id = 57,
                            Answer0 = "Automatically deploy code to production",
                            Answer1 = "Request that changes from one branch be reviewed and merged into another",
                            Answer2 = "Delete unused branches",
                            Answer3 = "Download changes from a remote repository",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "What is the main purpose of a pull request in Git-based platforms?"
                        },
                        new
                        {
                            Id = 58,
                            Answer0 = "Delete a repository",
                            Answer1 = "Manage parallel versions of code",
                            Answer2 = "Upload code to GitHub",
                            Answer3 = "Compile the project",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "What is the purpose of 'git branch'?"
                        },
                        new
                        {
                            Id = 59,
                            Answer0 = "Promises",
                            Answer1 = "Interfaces",
                            Answer2 = "Generics",
                            Answer3 = "Namespaces",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which JavaScript feature allows functions to run asynchronously without blocking execution?"
                        },
                        new
                        {
                            Id = 60,
                            Answer0 = "JavaScript",
                            Answer1 = "Python",
                            Answer2 = "Java",
                            Answer3 = "PHP",
                            CorrectIndex = 2,
                            Difficulty = 2,
                            Question = "Which of the following is a strongly typed language?"
                        },
                        new
                        {
                            Id = 61,
                            Answer0 = "Compile source code",
                            Answer1 = "Handle requests before reaching route handlers",
                            Answer2 = "Render HTML templates",
                            Answer3 = "Store database records",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "What is the purpose of middleware in web frameworks?"
                        },
                        new
                        {
                            Id = 62,
                            Answer0 = "PUT",
                            Answer1 = "GET",
                            Answer2 = "POST",
                            Answer3 = "TRACE",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which HTTP method is typically used to update an existing resource completely?"
                        },
                        new
                        {
                            Id = 63,
                            Answer0 = "200",
                            Answer1 = "401",
                            Answer2 = "404",
                            Answer3 = "302",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Which HTTP status code indicates the user is not authorized?"
                        },
                        new
                        {
                            Id = 64,
                            Answer0 = "XML",
                            Answer1 = "JSON",
                            Answer2 = "CSV",
                            Answer3 = "Binary",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Which format is most commonly used for REST API responses?"
                        },
                        new
                        {
                            Id = 65,
                            Answer0 = "Hooks",
                            Answer1 = "Templates",
                            Answer2 = "Modules",
                            Answer3 = "Services",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which React feature allows components to maintain internal state?"
                        },
                        new
                        {
                            Id = 66,
                            Answer0 = "Services",
                            Answer1 = "Pipes",
                            Answer2 = "Templates",
                            Answer3 = "Directives",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which Angular feature is used for dependency injection?"
                        },
                        new
                        {
                            Id = 67,
                            Answer0 = "Vitest",
                            Answer1 = "Webpack",
                            Answer2 = "Babel",
                            Answer3 = "Prettier",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which tool is commonly used for modern JavaScript unit testing?"
                        },
                        new
                        {
                            Id = 68,
                            Answer0 = "Cypress",
                            Answer1 = "Prettier",
                            Answer2 = "Babel",
                            Answer3 = "Lodash",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which tool is commonly used for browser-based end-to-end testing?"
                        },
                        new
                        {
                            Id = 69,
                            Answer0 = "Builds an image",
                            Answer1 = "Starts a container from an image",
                            Answer2 = "Deletes a container",
                            Answer3 = "Uploads images",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "What does 'docker run' do?"
                        },
                        new
                        {
                            Id = 70,
                            Answer0 = "Graph database",
                            Answer1 = "Document database",
                            Answer2 = "Relational database",
                            Answer3 = "Key-value store",
                            CorrectIndex = 2,
                            Difficulty = 2,
                            Question = "Which database type stores data in tables with rows and columns?"
                        },
                        new
                        {
                            Id = 71,
                            Answer0 = "UPDATE",
                            Answer1 = "MODIFY",
                            Answer2 = "ALTER",
                            Answer3 = "CHANGE",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which SQL command modifies existing data in a table?"
                        },
                        new
                        {
                            Id = 72,
                            Answer0 = "ORDER BY",
                            Answer1 = "GROUP BY",
                            Answer2 = "WHERE",
                            Answer3 = "LIMIT",
                            CorrectIndex = 2,
                            Difficulty = 2,
                            Question = "Which SQL clause filters query results?"
                        },
                        new
                        {
                            Id = 73,
                            Answer0 = "Application Programming Interface",
                            Answer1 = "Application Process Integration",
                            Answer2 = "Automated Program Interaction",
                            Answer3 = "Advanced Protocol Interface",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "What does API stand for?"
                        },
                        new
                        {
                            Id = 74,
                            Answer0 = "JSON.stringify()",
                            Answer1 = "JSON.parse()",
                            Answer2 = "JSON.object()",
                            Answer3 = "JSON.decode()",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Which JavaScript function converts JSON text into an object?"
                        },
                        new
                        {
                            Id = 75,
                            Answer0 = "Encapsulation",
                            Answer1 = "Inheritance",
                            Answer2 = "Abstraction",
                            Answer3 = "Polymorphism",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Which programming concept allows one class to inherit properties from another?"
                        },
                        new
                        {
                            Id = 76,
                            Answer0 = "200",
                            Answer1 = "302",
                            Answer2 = "404",
                            Answer3 = "500",
                            CorrectIndex = 3,
                            Difficulty = 2,
                            Question = "Which HTTP status code indicates a server error?"
                        },
                        new
                        {
                            Id = 77,
                            Answer0 = "Continuous Integration",
                            Answer1 = "Code Integration",
                            Answer2 = "Central Integration",
                            Answer3 = "Continuous Inspection",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "What does CI in CI/CD stand for?"
                        },
                        new
                        {
                            Id = 78,
                            Answer0 = "docker show",
                            Answer1 = "docker ps",
                            Answer2 = "docker list",
                            Answer3 = "docker containers",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Which Docker command lists running containers?"
                        },
                        new
                        {
                            Id = 79,
                            Answer0 = "git push",
                            Answer1 = "git commit",
                            Answer2 = "git add",
                            Answer3 = "git fetch",
                            CorrectIndex = 0,
                            Difficulty = 2,
                            Question = "Which Git command sends commits to a remote repository?"
                        },
                        new
                        {
                            Id = 80,
                            Answer0 = "await",
                            Answer1 = "async",
                            Answer2 = "defer",
                            Answer3 = "promise",
                            CorrectIndex = 1,
                            Difficulty = 2,
                            Question = "Which JavaScript keyword is used to define asynchronous functions?"
                        },
                        new
                        {
                            Id = 81,
                            Answer0 = "Authorization",
                            Answer1 = "Cache-Control",
                            Answer2 = "Content-Type",
                            Answer3 = "Expires-At",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which HTTP header is primarily used to control caching behavior?"
                        },
                        new
                        {
                            Id = 82,
                            Answer0 = "Reduces server memory usage",
                            Answer1 = "Forces clients to load the latest version of a resource",
                            Answer2 = "Encrypts cached files",
                            Answer3 = "Deletes server cache automatically",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What does cache busting typically achieve?"
                        },
                        new
                        {
                            Id = 83,
                            Answer0 = "Changing HTTP method",
                            Answer1 = "Adding version/hash to file names",
                            Answer2 = "Using POST requests",
                            Answer3 = "Clearing cookies",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which technique is commonly used for cache busting static assets?"
                        },
                        new
                        {
                            Id = 84,
                            Answer0 = "Communication between containers on the same host",
                            Answer1 = "Direct access to host kernel",
                            Answer2 = "Cross-cloud deployment",
                            Answer3 = "Persistent storage",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "In Docker, what does a bridge network allow?"
                        },
                        new
                        {
                            Id = 85,
                            Answer0 = "Expose container port to host",
                            Answer1 = "Limit CPU usage",
                            Answer2 = "Bind volumes",
                            Answer3 = "Set environment variables",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "What is the purpose of Docker port mapping (e.g., -p 80:3000)?"
                        },
                        new
                        {
                            Id = 86,
                            Answer0 = "Server memory leaks",
                            Answer1 = "Trust in authenticated user sessions",
                            Answer2 = "Weak encryption",
                            Answer3 = "SQL queries",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What vulnerability does CSRF exploit?"
                        },
                        new
                        {
                            Id = 87,
                            Answer0 = "Hashing passwords",
                            Answer1 = "CSRF tokens",
                            Answer2 = "Using GET requests",
                            Answer3 = "Minifying JavaScript",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which is a common mitigation against CSRF attacks?"
                        },
                        new
                        {
                            Id = 88,
                            Answer0 = "MVC uses controllers, Razor Pages are page-focused",
                            Answer1 = "MVC cannot use models",
                            Answer2 = "Razor Pages cannot access databases",
                            Answer3 = "MVC is frontend only",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "What is a key difference between ASP.NET MVC and Razor Pages?"
                        },
                        new
                        {
                            Id = 89,
                            Answer0 = "It returns data (e.g., JSON) instead of views",
                            Answer1 = "It cannot use routing",
                            Answer2 = "It only supports SOAP",
                            Answer3 = "It runs only on Windows",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "What distinguishes ASP.NET Web API from MVC?"
                        },
                        new
                        {
                            Id = 90,
                            Answer0 = "Supports advanced data types like JSONB",
                            Answer1 = "Only supports small datasets",
                            Answer2 = "Does not use SQL",
                            Answer3 = "Runs only locally",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "What is a common advantage of PostgreSQL over some other SQL databases?"
                        },
                        new
                        {
                            Id = 91,
                            Answer0 = "It only handles the UI layer",
                            Answer1 = "It includes backend support",
                            Answer2 = "It enforces strict project structure",
                            Answer3 = "It replaces databases",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "Why is React considered a library rather than a full framework?"
                        },
                        new
                        {
                            Id = 92,
                            Answer0 = "It enforces a specific project structure and patterns",
                            Answer1 = "It supports only one browser",
                            Answer2 = "It cannot use APIs",
                            Answer3 = "It encourages TypeScript",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "What does it mean that Angular is 'opinionated'?"
                        },
                        new
                        {
                            Id = 93,
                            Answer0 = "Django",
                            Answer1 = "Laravel",
                            Answer2 = "Express.js",
                            Answer3 = "ASP.NET",
                            CorrectIndex = 2,
                            Difficulty = 3,
                            Question = "Which of the following is NOT a batteries-included framework?"
                        },
                        new
                        {
                            Id = 94,
                            Answer0 = "LEFT JOIN",
                            Answer1 = "RIGHT JOIN",
                            Answer2 = "INNER JOIN",
                            Answer3 = "FULL JOIN",
                            CorrectIndex = 2,
                            Difficulty = 3,
                            Question = "Which SQL JOIN returns only matching rows from both tables?"
                        },
                        new
                        {
                            Id = 95,
                            Answer0 = "INNER JOIN",
                            Answer1 = "LEFT JOIN",
                            Answer2 = "RIGHT JOIN",
                            Answer3 = "CROSS JOIN",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which SQL JOIN returns all rows from the left table and matching from the right?"
                        },
                        new
                        {
                            Id = 96,
                            Answer0 = "Measuring memory allocation",
                            Answer1 = "Describing algorithm time complexity",
                            Answer2 = "Defining syntax rules",
                            Answer3 = "Compiling code",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What is Big-O notation used for?"
                        },
                        new
                        {
                            Id = 97,
                            Answer0 = "O(n)",
                            Answer1 = "O(log n)",
                            Answer2 = "O(n log n)",
                            Answer3 = "O(1)",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What is the time complexity of binary search?"
                        },
                        new
                        {
                            Id = 98,
                            Answer0 = "Single-thread execution",
                            Answer1 = "Multiple threads accessing shared data without synchronization",
                            Answer2 = "Using constants",
                            Answer3 = "Reading files sequentially",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which scenario commonly causes a race condition?"
                        },
                        new
                        {
                            Id = 99,
                            Answer0 = "Cross-Origin Resource Sharing",
                            Answer1 = "Cross Object Request System",
                            Answer2 = "Client Origin Resource Sync",
                            Answer3 = "Cross Output Routing Standard",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "What does CORS stand for?"
                        },
                        new
                        {
                            Id = 100,
                            Answer0 = "Invalid HTML",
                            Answer1 = "Cross-origin requests without proper headers",
                            Answer2 = "Slow server response",
                            Answer3 = "Missing CSS",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What triggers a CORS error in browsers?"
                        },
                        new
                        {
                            Id = 101,
                            Answer0 = "Expose ports",
                            Answer1 = "Persist data outside containers",
                            Answer2 = "Limit memory usage",
                            Answer3 = "Run multiple containers",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What is the purpose of a Docker volume?"
                        },
                        new
                        {
                            Id = 102,
                            Answer0 = "null",
                            Answer1 = "object",
                            Answer2 = "undefined",
                            Answer3 = "number",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What is the output of the following JavaScript code: console.log(typeof null);"
                        },
                        new
                        {
                            Id = 103,
                            Answer0 = "true",
                            Answer1 = "false",
                            Answer2 = "undefined",
                            Answer3 = "error",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "What is the output of: console.log(0 == false);"
                        },
                        new
                        {
                            Id = 104,
                            Answer0 = "true",
                            Answer1 = "false",
                            Answer2 = "undefined",
                            Answer3 = "error",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What is the output of: console.log(0 === false);"
                        },
                        new
                        {
                            Id = 105,
                            Answer0 = "400",
                            Answer1 = "401",
                            Answer2 = "403",
                            Answer3 = "429",
                            CorrectIndex = 3,
                            Difficulty = 3,
                            Question = "Which HTTP status code indicates 'Too Many Requests'?"
                        },
                        new
                        {
                            Id = 106,
                            Answer0 = "Content-Type",
                            Answer1 = "Authorization",
                            Answer2 = "Cache-Control",
                            Answer3 = "Accept",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which HTTP header is commonly used for authentication tokens?"
                        },
                        new
                        {
                            Id = 107,
                            Answer0 = "Database optimization",
                            Answer1 = "Injecting malicious scripts into web pages",
                            Answer2 = "Improving performance",
                            Answer3 = "Encrypting data",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What is XSS primarily used for by attackers?"
                        },
                        new
                        {
                            Id = 108,
                            Answer0 = "String concatenation",
                            Answer1 = "Parameterized queries",
                            Answer2 = "Using GET requests",
                            Answer3 = "Disabling validation",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which practice helps prevent SQL injection?"
                        },
                        new
                        {
                            Id = 109,
                            Answer0 = "To block execution until the response arrives",
                            Answer1 = "To handle asynchronous responses in a readable, sequential way",
                            Answer2 = "To speed up network requests",
                            Answer3 = "To avoid using HTTP methods",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Why is async/await commonly used when making backend API calls?"
                        },
                        new
                        {
                            Id = 110,
                            Answer0 = "Bubble sort",
                            Answer1 = "Quick sort",
                            Answer2 = "Linear search",
                            Answer3 = "Selection sort",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which sorting algorithm typically has O(n log n) complexity?"
                        },
                        new
                        {
                            Id = 111,
                            Answer0 = "true",
                            Answer1 = "false",
                            Answer2 = "undefined",
                            Answer3 = "error",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "What is the output of: console.log([] == false);"
                        },
                        new
                        {
                            Id = 112,
                            Answer0 = "true",
                            Answer1 = "false",
                            Answer2 = "undefined",
                            Answer3 = "error",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What is the output of: console.log([] === false);"
                        },
                        new
                        {
                            Id = 113,
                            Answer0 = "no-store",
                            Answer1 = "max-age=0",
                            Answer2 = "immutable",
                            Answer3 = "private",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which HTTP caching directive forces revalidation with the server?"
                        },
                        new
                        {
                            Id = 114,
                            Answer0 = "bridge",
                            Answer1 = "host",
                            Answer2 = "overlay",
                            Answer3 = "none",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which Docker network mode gives a container direct access to the host network?"
                        },
                        new
                        {
                            Id = 115,
                            Answer0 = "3",
                            Answer1 = "52",
                            Answer2 = "NaN",
                            Answer3 = "error",
                            CorrectIndex = 0,
                            Difficulty = 3,
                            Question = "What is the output of: console.log('5' - 2);"
                        },
                        new
                        {
                            Id = 116,
                            Answer0 = "7",
                            Answer1 = "52",
                            Answer2 = "NaN",
                            Answer3 = "error",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What is the output of: console.log('5' + 2);"
                        },
                        new
                        {
                            Id = 117,
                            Answer0 = "Factory",
                            Answer1 = "Singleton",
                            Answer2 = "Observer",
                            Answer3 = "Adapter",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which concept ensures only one instance of a class exists?"
                        },
                        new
                        {
                            Id = 118,
                            Answer0 = "POST",
                            Answer1 = "PUT",
                            Answer2 = "PATCH",
                            Answer3 = "CONNECT",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which HTTP method is idempotent?"
                        },
                        new
                        {
                            Id = 119,
                            Answer0 = "NaN",
                            Answer1 = "number",
                            Answer2 = "undefined",
                            Answer3 = "object",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "What is the output of: console.log(typeof NaN);"
                        },
                        new
                        {
                            Id = 120,
                            Answer0 = "B-Tree only",
                            Answer1 = "GIN index",
                            Answer2 = "Flat index",
                            Answer3 = "Heap index",
                            CorrectIndex = 1,
                            Difficulty = 3,
                            Question = "Which PostgreSQL feature allows indexing JSON data efficiently?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
